// <auto-generated />
using System;
using Drones.Infrastructure.Persistences.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drones.Infrastructure.Migrations
{
    [DbContext(typeof(DronesContext))]
    [Migration("20260421210823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Modern_Spanish_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drones.Domain.Entities.NModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("nModel", (string)null);
                });

            modelBuilder.Entity("Drones.Domain.Entities.NState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("nState", (string)null);
                });

            modelBuilder.Entity("Drones.Domain.Entities.RDroneMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateOpperation")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDrone")
                        .HasColumnType("int");

                    b.Property<int>("IdMedication")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDrone");

                    b.HasIndex("IdMedication");

                    b.ToTable("rDroneMedication", (string)null);
                });

            modelBuilder.Entity("Drones.Domain.Entities.TDrone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BatteryCapacity")
                        .HasColumnType("float");

                    b.Property<double>("BatteryLevel")
                        .HasColumnType("float");

                    b.Property<int>("Model")
                        .HasColumnType("int");

                    b.Property<int?>("NModelId")
                        .HasColumnType("int");

                    b.Property<int?>("NStateId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<double>("WeightLimit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NModelId");

                    b.HasIndex("NStateId");

                    b.ToTable("tDrone", (string)null);
                });

            modelBuilder.Entity("Drones.Domain.Entities.TMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tMedication", (string)null);
                });

            modelBuilder.Entity("Drones.Domain.Entities.RDroneMedication", b =>
                {
                    b.HasOne("Drones.Domain.Entities.TDrone", "IdDroneNavigation")
                        .WithMany("RDroneMedications")
                        .HasForeignKey("IdDrone")
                        .IsRequired()
                        .HasConstraintName("FK_rDroneMedication_tDrone");

                    b.HasOne("Drones.Domain.Entities.TMedication", "IdMedicationNavigation")
                        .WithMany("RDroneMedications")
                        .HasForeignKey("IdMedication")
                        .IsRequired()
                        .HasConstraintName("FK_rDroneMedication_tMedication");

                    b.Navigation("IdDroneNavigation");

                    b.Navigation("IdMedicationNavigation");
                });

            modelBuilder.Entity("Drones.Domain.Entities.TDrone", b =>
                {
                    b.HasOne("Drones.Domain.Entities.NModel", null)
                        .WithMany("TDrones")
                        .HasForeignKey("NModelId");

                    b.HasOne("Drones.Domain.Entities.NState", null)
                        .WithMany("TDrones")
                        .HasForeignKey("NStateId");
                });

            modelBuilder.Entity("Drones.Domain.Entities.NModel", b =>
                {
                    b.Navigation("TDrones");
                });

            modelBuilder.Entity("Drones.Domain.Entities.NState", b =>
                {
                    b.Navigation("TDrones");
                });

            modelBuilder.Entity("Drones.Domain.Entities.TDrone", b =>
                {
                    b.Navigation("RDroneMedications");
                });

            modelBuilder.Entity("Drones.Domain.Entities.TMedication", b =>
                {
                    b.Navigation("RDroneMedications");
                });
#pragma warning restore 612, 618
        }
    }
}
